name: api_client
description: Generated Dart SDK for Audio Guide 2026 API.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
