name: mobile_flutter
description: Audiogid mobile application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  dio: ^5.4.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  riverpod_annotation: ^4.0.2
  uuid: ^4.3.3
  api_client:
    path: ../../packages/api_client
  flutter_secure_storage: ^10.0.0

  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  flutter_map_marker_cluster: ^8.2.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.5
  vector_math: ^2.1.4
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  audio_service: ^0.18.12
  rxdart: ^0.28.0
  in_app_purchase: ^3.1.13
  package_info_plus: ^9.0.0
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: ^0.4.7
  flutter_downloader: ^1.11.0
  archive: ^4.0.9
  crypto: ^3.0.3
  mobile_scanner: ^7.2.0
  flutter_local_notifications: ^21.0.0-dev.1
  share_plus: ^12.0.1
  app_links: ^7.0.0
  timezone: ^0.11.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  flutter_localizations:
    sdk: flutter
  in_app_review: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/store/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/store/icon.png"
