name: mobile_flutter
description: Audiogid mobile application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  dio: ^5.4.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  riverpod_annotation: ^2.3.3
  uuid: ^4.3.3
  api_client:
    path: ../../packages/api_client
  flutter_secure_storage: ^9.0.0

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  flutter_map_marker_cluster: ^1.3.1
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  vector_math: ^2.1.4
  vector_map_tiles: ^3.0.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  rxdart: ^0.27.7
  in_app_purchase: ^3.1.13
  package_info_plus: ^5.0.1
  in_app_purchase_android: ^0.3.0
  in_app_purchase_storekit: ^0.3.0
  flutter_downloader: ^1.11.0
  archive: ^3.3.7
  crypto: ^3.0.3
  disk_space_2: ^2.0.1
  mobile_scanner: ^5.0.0
  flutter_local_notifications: ^16.3.2
  share_plus: ^7.2.1
  app_links: ^3.5.0
  timezone: ^0.9.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_jailbreak_detection: ^1.0.0
  in_app_review: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  mocktail_image_network: ^0.8.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/store/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/store/icon.png"
